name: Compile

on:
  workflow_dispatch:

jobs:
  Compiling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.4'
      - run: go version
      - name: Compile binary files for each platform.
        run: make VERSION=${{ github.ref_name}}
      - name: Upload artifact(windows_arm64)
        uses: actions/upload-artifact@main
        with:
          name: windows_arm64
          path: dist/rikka_${{ github.ref_name}}_windows_arm64.exe
      - name: Upload artifact(windows_amd64)
        uses: actions/upload-artifact@main
        with:
          name: windows_amd64
          path: dist/rikka_${{ github.ref_name}}_windows_amd64.exe
      - name: Upload artifact(linux_arm64)
        uses: actions/upload-artifact@main
        with:
          name: linux_arm64
          path: dist/rikka_${{ github.ref_name}}_linux_arm64
      - name: Upload artifact(linux_amd64)
        uses: actions/upload-artifact@main
        with:
          name: linux_amd64
          path: dist/rikka_${{ github.ref_name}}_linux_amd64
      - name: Upload artifact(darwin_arm64)
        uses: actions/upload-artifact@main
        with:
          name: darwin_arm64
          path: dist/rikka_${{ github.ref_name}}_darwin_arm64
      - name: Upload artifact(darwin_amd64)
        uses: actions/upload-artifact@main
        with:
          name: darwin_amd64
          path: dist/rikka_${{ github.ref_name}}_darwin_amd64

